# Basic
name:               "epistrephein"

author:
  name:             epistrephein
  github:           epistrephein
  email:            epistrephein@gmail.com

# Google-analytics
google-analytics:
  id:               "UA-61290809-3"

# Disqus
disqus:
  id:               "epistrephein"

# URL
url:                "http://epistrephe.in"
baseurl:            "" # the subpath of your site, e.g. /blog

# Timezone
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Rome
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "Archive"
    url:            "/archive"
  - name:           "Github"
    url:            "https://github.com/epistrephein"
  - name:           "Email"
    url:            "mailto:epistrephein@gmail.com"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
